### ISSUE TITLE
review terminology page

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-docs#119]
https://docs.easybuild.io/terminology

**Comment by PetrKralCZ** [comment]
- the `|version|` in the sentence: "In EasyBuild version |version| the framework source code consists of about 19000 lines of code"
- quite an old version in the sentence: "EasyBuild version 2.4.0 includes 154 software-specific easyblocks and 28 generic easyblocks"
- Everything else seems OK to me.

**Comment by boegel** [comment]
Instead of `|version|`, we can use `{{ easybuild.version }}` (see how it's used in `docs/index.md`).
That will probably only work outside of code blocks though (to be checked).

That sentence only mentioning an ancient EasyBuild version can be removed - correct counts are kept on top of https://docs.easybuild.io/release-notes .

@PetrKralCZ Are you up for making a small PR for this?

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-docs/pull/133
