### ISSUE TITLE
review backup-modules page

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-docs#139]
https://docs.easybuild.io/backup-modules

**Comment by PetrKralCZ** [comment]
- We could maybe update the example? The example shows actions with `bzip2 1.0.6` easyconfig. We already have an easyconfig for `bzip2 1.0.8`.
- I haven't found anything else to to be changed there.

**Comment by PetrKralCZ** [comment]
- https://github.com/easybuilders/easybuild-docs/pull/147
