### ISSUE TITLE
Main website still refers to IRC @ Freenode

### ISSUE THREAD

**Issue by hattom** [easybuilders/easybuild-docs#206]
I thought I made an issue once before, but I don't find it anymore.
In any case, it probably slipped through the cracks.

On the main website: https://easybuild.io/, we have:
```
Slack/IRC
Contact the EasyBuild community via Slack: https://easybuild.slack.com/,
self-request an invite via https://easybuild.io/join-slack.

An IRC channel #easybuild has been set up on the FreeNode network.

Just connect your IRC client to the chat.freenode.net server, and join the #easybuild channel.
```

I guess it's `s/freenode/liberachat/`, though I never looked at the IRC channel, so I'm not sure where it lives exactly?

**Comment by boegel** [comment]
fixed in https://github.com/easybuilders/easybuild/commit/19b6bc9c0c301e11962510e82a8a009f5e6e7c80
