### ISSUE TITLE
Internal links in auto-generated content

### ISSUE THREAD

**Issue by orbsmiv** [easybuilders/easybuild-docs#24]
In order to preserve the current docs' internal links, the auto-generated content (e.g. that in `version-specific` directory) will need to include the following links as attributes (e.g. `{: #link_name }`):

*(N.B. please update the following list as instances are discovered.)*

* `version-specific/eb-list-toolchains.md`:
  * `toolchains_table`
* `version-specific/toolchain-opts.md`:
  * `avail_toolchain_opts`
* `version-specific/eb-a-wrf.md`:
  * `eb_a_e_EB_WRF`
* `version-specific/help.md`
  * `basic_usage_help`
* `version-specific/easyconfig_parameters.md`
  * `easyconfig_params`

**Comment by branfosj** [comment]
done in #86
