### ISSUE TITLE
port over recent documentation changes

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-docs#66]
* [x] https://github.com/easybuilders/easybuild/pull/832 - #67

**Comment by branfosj** [comment]
closing, as there have been no recent changes and all future changes should be made here instead of the old docs.

**Comment by boegel** [comment]
> closing, as there have been no recent changes and all future changes should be made here instead of the old docs.

We'll definitely need to port of the release notes for EasyBuild v4.7.0 first (release is scheduled for Mon 9 Jan).

Then we can switch over the docs (there's a handful of small things that still need to be done, like fleshing out the menu and landing page, and replacing the old docs with a landing page that points to the new docs + putting a nice 404 page in place there too)

**Comment by branfosj** [comment]
We've switched over the docs, so closing this.
